In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/cleaned/Metallic Glass Transition Data/Metallic_Glass_Forming_with_features_CLEANED.csv")

In [2]:
df.head()

,Material compositions,Trg,Density_composition_average,IsBoron_composition_average,IsDBlock_composition_average,NdValence_composition_average,NValance_composition_average,HeatVaporization_max_value,BoilingT_difference,HeatVaporization_difference,...,Nb,Mg,Gd,La,Zr,P,Cr,Ni,Ag,C
0,Ag10Cu35Zr55,0.534,0.579069,-0.5856,1.029882,0.589536,0.217571,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,55.0,0.0,0.0,0.0,10.0,0.0
1,Ag10Cu50Zr40,0.608,0.748401,-0.5856,1.029882,1.176250,0.653969,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,10.0,0.0
2,Ag10Cu55Zr35,0.609,0.804845,-0.5856,1.029882,1.371822,0.799435,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,10.0,0.0
3,Ag20Cu40Zr40,0.577,0.821973,-0.5856,1.029882,1.176250,0.653969,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,0.0,40.0,0.0,0.0,0.0,20.0,0.0
4,Ag35Ca65,0.515,-0.860992,-0.5856,-0.998961,-0.437214,-0.613663,-1.684370,-1.368929,-1.228445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0

In [3]:
df.shape

(537, 48)

In [4]:
all_num_elements = []
for comp_str in df.iloc[:, 0]:
    num_elements = 0
    for c in comp_str:
        if c.isalpha() and c == c.upper(): num_elements += 1
    all_num_elements.append(num_elements)
print(all_num_elements)

[3, 3, 3, 3, 2, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 4, 3, 3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 3, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 5, 4, 6, 5, 5, 5, 5, 2, 2, 2, 4, 4, 4, 4, 4, 4, 2, 3, 4, 4, 4, 4, 4, 4, 3, 4, 4, 5, 4, 4, 4, 3, 4, 4, 4, 3, 3, 2, 4, 4, 4, 3, 3, 3, 2, 4, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 4, 4, 3, 3, 3, 2, 5, 4, 4, 3, 4, 4, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 4, 4, 2, 4, 3, 3, 3, 2, 4, 2, 3, 4, 4, 3, 3, 4, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 5, 4, 7, 5, 7, 6, 7, 5, 7, 7, 6, 6, 5, 4, 7, 5, 4, 6, 4, 7, 7, 6, 4, 5, 5, 4, 4, 4, 4, 4, 4, 4, 5, 5, 4, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 4, 3, 2, 2, 4, 3, 3, 4, 4, 4, 4, 6, 6, 5, 6, 6, 4, 4, 4, 4, 3, 4, 4, 3, 5, 4, 4, 5, 5, 5, 5, 4, 6, 5, 4, 4, 4, 4, 4, 4, 3, 4, 4, 6, 3, 2, 2, 4, 4, 4, 3, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 4, 3, 3, 3, 4, 3, 3, 3, 3, 4, 4, 4, 3, 6, 7, 7, 7, 6, 3, 2, 3, 3, 3, 3, 3, 2, 5, 3, 5, 2, 2, 2, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5, 4, 4, 3, 3, 3, 3, 3, 2, 5, 5, 5, 5, 4, 5, 2, 2, 2, 4, 3, 3, 2, 4, 4, 4, 4, 4, 4, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 3, 3, 3, 3, 5, 5, 5, 5, 4, 2, 3, 3, 2, 2, 2, 2, 2, 3, 3, 4, 4, 3, 2, 4, 4, 4, 4, 4, 4, 4, 5, 7, 6, 5, 6, 4, 3, 5, 4, 6, 4, 5, 7, 7, 5, 5, 2, 4, 5, 4, 3, 3, 7, 8, 7, 5, 5, 7, 5, 6, 6, 5, 3, 5, 5, 3, 3, 3, 5, 5, 5, 3, 3, 3, 3, 5, 4, 4, 4, 4, 4, 3, 5, 5, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 5, 3, 5, 5, 3, 3, 3, 3, 3, 3, 5, 5, 5, 3, 3, 3, 4, 4, 4, 4, 4, 4, 2, 4, 4, 3, 4]

In [5]:
df["Number_elements"] = all_num_elements

In [6]:
df.head()

,Material compositions,Trg,Density_composition_average,IsBoron_composition_average,IsDBlock_composition_average,NdValence_composition_average,NValance_composition_average,HeatVaporization_max_value,BoilingT_difference,HeatVaporization_difference,...,Mg,Gd,La,Zr,P,Cr,Ni,Ag,C,Number_elements
0,Ag10Cu35Zr55,0.534,0.579069,-0.5856,1.029882,0.589536,0.217571,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,55.0,0.0,0.0,0.0,10.0,0.0,3
1,Ag10Cu50Zr40,0.608,0.748401,-0.5856,1.029882,1.176250,0.653969,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,40.0,0.0,0.0,0.0,10.0,0.0,3
2,Ag10Cu55Zr35,0.609,0.804845,-0.5856,1.029882,1.371822,0.799435,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,35.0,0.0,0.0,0.0,10.0,0.0,3
3,Ag20Cu40Zr40,0.577,0.821973,-0.5856,1.029882,1.176250,0.653969,0.563915,0.544521,0.505748,...,0.0,0.0,0.0,40.0,0.0,0.0,0.0,20.0,0.0,3
4,Ag35Ca65,0.515,-0.860992,-0.5856,-0.998961,-0.437214,-0.613663,-1.684370,-1.368929,-1.228445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0,2

In [7]:
from matminer.utils.data import MixingEnthalpy
from pymatgen.core import Composition, Element
from matminer.featurizers.composition.alloy import WenAlloys
from matminer.featurizers.composition import ElementProperty
import itertools

In [8]:
wen = WenAlloys(impute_nan=True)
mix_enthalpy_table = MixingEnthalpy(impute_nan=True)

In [9]:
def calculate_wenalloy_features(composition_str, verbose=False):
    comp = Composition(composition_str)

    elements = [Element(str(e)) for e in comp.elements]
    fractions = [comp.get_atomic_fraction(e) for e in comp.elements]
    radii = [e.atomic_radius for e in elements]

    delta = wen.compute_delta(radii, fractions)
    entropy = abs(wen.compute_configuration_entropy(fractions))

    enthalpy = 0
    for (e1, e2) in itertools.combinations(elements, 2):
        c1 = comp.get_atomic_fraction(e1)
        c2 = comp.get_atomic_fraction(e2)
        h_ij = mix_enthalpy_table.get_mixing_enthalpy(e1, e2)
        if h_ij is None:
            h_ij = 0
        pair_contribution = 4 * c1 * c2 * h_ij
        enthalpy += pair_contribution
        if verbose:
            print(f"{e1}-{e2}: ΔH = {h_ij:+.2f} kJ/mol, "
                      f"weighted = {pair_contribution:+.4f}")

    if verbose:
        print(f"\nComposition: {composition_str}")
        print(f"Δ (atomic size mismatch): {delta:.4f}")
        print(f"ΔH_mix (total): {enthalpy:.4f}")
        print(f"ΔS_conf: {entropy:.4f}")
        print("---- Binary contributions ----")

    # magpie_features_dict = {}
    # if df is not None:
    #     ep = ElementProperty.from_preset("magpie")
    #     # Prepare a temporary DataFrame for this single composition
    #     temp_df = pd.DataFrame({"composition": [composition_str]})
    #     temp_df = ep.featurize_dataframe(temp_df, "composition", ignore_errors=True)
    #     magpie_features_dict = temp_df.drop(columns=["composition"]).iloc[0].to_dict()
    
    return delta, enthalpy, entropy

In [10]:
from matminer.featurizers.composition.alloy import Miedema

In [11]:
midema = Miedema(impute_nan=True)

In [12]:
def calculate_miedema_features(composition_str, Trg, mixing_enthalpy, verbose=False):
    comp = Composition(composition_str)

    elements = [Element(str(e)) for e in comp.elements]
    fractions = [comp.get_atomic_fraction(e) for e in comp.elements]
    radii = [e.atomic_radius for e in elements]

    # struct = ""
    # if mixing_enthalpy < -10:
    #     struct = 'inter'
    # elif trg >= 0.625 and -10 <= mixing_enthalpy <= 0:
    #     struct = 'amor'
    # else:
    #     struct = 'ss'

    sorted_indices = np.argsort(fractions)[::-1]  # largest fractions first
    top_elements = [str(comp.elements[i]) for i in sorted_indices[:2]]
    top_fracs = [fractions[i] for i in sorted_indices[:2]]

    deltaH = midema.deltaH_chem(top_elements, top_fracs, 'amor')
    # standard_deltaH = midema.deltaH_chem(top_elements, top_fracs, "all")
    deltaH_topo = midema.deltaH_topo([str(e) for e in comp.elements], fractions)

    return deltaH, deltaH_topo

In [22]:
from matminer.featurizers.composition.element import BandCenter

In [27]:
bandObj = BandCenter(impute_nan=True)

In [34]:
def calculate_band_features(composition_str, verbose=False):
    comp = Composition(composition_str)

    return bandObj.featurize(comp)[0]

In [35]:
# delta, enthalpy, entropy, sign_error = calculate_wenalloy_features("Ag10Cu35Zr55", verbose=False)
# sign_error

# From investigation, it appears that the manually calculated enthalpies match the wen alloy calculated enthalpies
# with differences only arising in opposite signage and magnitude differnces on the order of magnitude of 10^-15
# However, ther is one entry with a differce that is about 11kj/mol, Mg65Zr35

In [36]:
atomic_size_mismatch = []
mixing_enthalpy = []
mixing_entropy = []
formation_amor = []
toplogical_formation = []
band_sizes = []
# standard_formation = []

for _, row in df.iterrows():
    comp_str = row['Material compositions']
    trg = row['Trg']  # pull Tg value for this row
    
    # WenAlloy features
    delta, enthalpy, entropy = calculate_wenalloy_features(comp_str)
    atomic_size_mismatch.append(delta)
    mixing_enthalpy.append(enthalpy)
    mixing_entropy.append(entropy)
    
    # Miedema formation enthalpy
    deltaH, deltaH_topo = calculate_miedema_features(comp_str, trg, enthalpy)
    formation_amor.append(deltaH)
    toplogical_formation.append(deltaH_topo)
    # standard_formation.append(standard_deltaH)

    # Band featurization
    band = calculate_band_features(comp_str)
    band_sizes.append(band)

In [37]:
# mixing_enthalpy

In [38]:
# me = MixingEnthalpy(impute_nan=True)
# print(me.get_mixing_enthalpy(Element("Zn"), Element("Ag")))  # example
# print(me.get_mixing_enthalpy(Element("Cu"), Element("Zr")))  # example

In [39]:
df["Atomic_size_mismatch"] = atomic_size_mismatch
df["Mixing_enthalpy"] = mixing_enthalpy
df["Mixing_entropy"] = mixing_entropy
df["Formation_amorphous"] = formation_amor
df["Topological_formation"] = toplogical_formation
df["Band sizes"] = band_sizes
# df["Standard_Formation"] = standard_formation

In [40]:
df.shape

(537, 55)

In [41]:
df.to_csv("../../data/cleaned/Metallic Glass Transition Data/Metallic_Glass_Forming_with_features_Matminer_Features.csv", index=False)